### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by eboileau** [eboileau/trackhub-utils#1]
- [ ] Add tests.
- [ ] Add documentation/examples.
- [ ] Add `trackhub@master` to requirements.
- [ ] Fix deepTools args (bamCoverage) in bam2bigWig.py.
- [ ] get-hub.py: fix staging/upload, copy/link source files; how to extend to composite and multiWig containers (via external ad hoc modules)?
